<?php

namespace App\Classes;

class BlockingSchedule
{
    public static function workOnWeekends($schedule)
    {
        if (!empty($schedule)) {
            $schedule = (array)$schedule;
            return count($schedule[6] ?? []) < 24 || count($schedule[7] ?? []) < 24;
        }
        return true;
    }

    public static function timezones()
    {
        return array(
            ''                     => "(GMT+3:00)",
            'Pacific/Midway'       => "(GMT-11:00) Midway Island",
            'US/Samoa'             => "(GMT-11:00) Samoa",
            'US/Hawaii'            => "(GMT-10:00) Hawaii",
            'US/Alaska'            => "(GMT-9:00) Alaska",
            'US/Pacific'           => "(GMT-8:00) Pacific Time (US &amp; Canada)",
            'America/Tijuana'      => "(GMT-8:00) Tijuana",
            'US/Arizona'           => "(GMT-7:00) Arizona",
            'US/Mountain'          => "(GMT-7:00) Mountain Time (US &amp; Canada)",
            'America/Chihuahua'    => "(GMT-7:00) Chihuahua",
            'America/Mazatlan'     => "(GMT-7:00) Mazatlan",
            'America/Mexico_City'  => "(GMT-6:00) Mexico City",
            'America/Monterrey'    => "(GMT-6:00) Monterrey",
            'Canada/Saskatchewan'  => "(GMT-6:00) Saskatchewan",
            'US/Central'           => "(GMT-6:00) Central Time (US &amp; Canada)",
            'US/Eastern'           => "(GMT-5:00) Eastern Time (US &amp; Canada)",
            'US/East-Indiana'      => "(GMT-5:00) Indiana (East)",
            'America/Bogota'       => "(GMT-5:00) Bogota",
            'America/Lima'         => "(GMT-5:00) Lima",
            'America/Caracas'      => "(GMT-4:30) Caracas",
            'Canada/Atlantic'      => "(GMT-4:00) Atlantic Time (Canada)",
            'America/La_Paz'       => "(GMT-4:00) La Paz",
            'America/Santiago'     => "(GMT-4:00) Santiago",
            'Canada/Newfoundland'  => "(GMT-3:30) Newfoundland",
            'America/Buenos_Aires' => "(GMT-3:00) Buenos Aires",
            'Greenland'            => "(GMT-3:00) Greenland",
            'Atlantic/Stanley'     => "(GMT-2:00) Stanley",
            'Atlantic/Azores'      => "(GMT-1:00) Azores",
            'Atlantic/Cape_Verde'  => "(GMT-1:00) Cape Verde Is.",
            'Africa/Casablanca'    => "(GMT) Casablanca",
            'Europe/Dublin'        => "(GMT) Dublin",
            'Europe/Lisbon'        => "(GMT) Lisbon",
            'Europe/London'        => "(GMT) London",
            'Africa/Monrovia'      => "(GMT) Monrovia",
            'Europe/Amsterdam'     => "(GMT+1:00) Amsterdam",
            'Europe/Belgrade'      => "(GMT+1:00) Belgrade",
            'Europe/Berlin'        => "(GMT+1:00) Berlin",
            'Europe/Bratislava'    => "(GMT+1:00) Bratislava",
            'Europe/Brussels'      => "(GMT+1:00) Brussels",
            'Europe/Budapest'      => "(GMT+1:00) Budapest",
            'Europe/Copenhagen'    => "(GMT+1:00) Copenhagen",
            'Europe/Ljubljana'     => "(GMT+1:00) Ljubljana",
            'Europe/Madrid'        => "(GMT+1:00) Madrid",
            'Europe/Paris'         => "(GMT+1:00) Paris",
            'Europe/Prague'        => "(GMT+1:00) Prague",
            'Europe/Rome'          => "(GMT+1:00) Rome",
            'Europe/Sarajevo'      => "(GMT+1:00) Sarajevo",
            'Europe/Skopje'        => "(GMT+1:00) Skopje",
            'Europe/Stockholm'     => "(GMT+1:00) Stockholm",
            'Europe/Vienna'        => "(GMT+1:00) Vienna",
            'Europe/Warsaw'        => "(GMT+1:00) Warsaw",
            'Europe/Zagreb'        => "(GMT+1:00) Zagreb",
            'Europe/Athens'        => "(GMT+2:00) Athens",
            'Europe/Bucharest'     => "(GMT+2:00) Bucharest",
            'Africa/Cairo'         => "(GMT+2:00) Cairo",
            'Africa/Harare'        => "(GMT+2:00) Harare",
            'Europe/Helsinki'      => "(GMT+2:00) Helsinki",
            'Europe/Istanbul'      => "(GMT+2:00) Istanbul",
            'Asia/Jerusalem'       => "(GMT+2:00) Jerusalem",
            'Europe/Kiev'          => "(GMT+2:00) Kyiv",
            'Europe/Minsk'         => "(GMT+2:00) Minsk",
            'Europe/Riga'          => "(GMT+2:00) Riga",
            'Europe/Sofia'         => "(GMT+2:00) Sofia",
            'Europe/Tallinn'       => "(GMT+2:00) Tallinn",
            'Europe/Vilnius'       => "(GMT+2:00) Vilnius",
            'Asia/Baghdad'         => "(GMT+3:00) Baghdad",
            'Asia/Kuwait'          => "(GMT+3:00) Kuwait",
            'Africa/Nairobi'       => "(GMT+3:00) Nairobi",
            'Asia/Riyadh'          => "(GMT+3:00) Riyadh",
            'Europe/Moscow'        => "(GMT+3:00) Moscow",
            'Asia/Tehran'          => "(GMT+3:30) Tehran",
            'Asia/Baku'            => "(GMT+4:00) Baku",
            'Europe/Volgograd'     => "(GMT+4:00) Volgograd",
            'Asia/Muscat'          => "(GMT+4:00) Muscat",
            'Asia/Tbilisi'         => "(GMT+4:00) Tbilisi",
            'Asia/Yerevan'         => "(GMT+4:00) Yerevan",
            'Asia/Kabul'           => "(GMT+4:30) Kabul",
            'Asia/Karachi'         => "(GMT+5:00) Karachi",
            'Asia/Tashkent'        => "(GMT+5:00) Tashkent",
            'Asia/Kolkata'         => "(GMT+5:30) Kolkata",
            'Asia/Kathmandu'       => "(GMT+5:45) Kathmandu",
            'Asia/Yekaterinburg'   => "(GMT+6:00) Ekaterinburg",
            'Asia/Almaty'          => "(GMT+6:00) Almaty",
            'Asia/Dhaka'           => "(GMT+6:00) Dhaka",
            'Asia/Novosibirsk'     => "(GMT+7:00) Novosibirsk",
            'Asia/Bangkok'         => "(GMT+7:00) Bangkok",
            'Asia/Jakarta'         => "(GMT+7:00) Jakarta",
            'Asia/Krasnoyarsk'     => "(GMT+8:00) Krasnoyarsk",
            'Asia/Chongqing'       => "(GMT+8:00) Chongqing",
            'Asia/Hong_Kong'       => "(GMT+8:00) Hong Kong",
            'Asia/Kuala_Lumpur'    => "(GMT+8:00) Kuala Lumpur",
            'Australia/Perth'      => "(GMT+8:00) Perth",
            'Asia/Singapore'       => "(GMT+8:00) Singapore",
            'Asia/Taipei'          => "(GMT+8:00) Taipei",
            'Asia/Ulaanbaatar'     => "(GMT+8:00) Ulaan Bataar",
            'Asia/Urumqi'          => "(GMT+8:00) Urumqi",
            'Asia/Irkutsk'         => "(GMT+9:00) Irkutsk",
            'Asia/Seoul'           => "(GMT+9:00) Seoul",
            'Asia/Tokyo'           => "(GMT+9:00) Tokyo",
            'Australia/Adelaide'   => "(GMT+9:30) Adelaide",
            'Australia/Darwin'     => "(GMT+9:30) Darwin",
            'Asia/Yakutsk'         => "(GMT+10:00) Yakutsk",
            'Australia/Brisbane'   => "(GMT+10:00) Brisbane",
            'Australia/Canberra'   => "(GMT+10:00) Canberra",
            'Pacific/Guam'         => "(GMT+10:00) Guam",
            'Australia/Hobart'     => "(GMT+10:00) Hobart",
            'Australia/Melbourne'  => "(GMT+10:00) Melbourne",
            'Pacific/Port_Moresby' => "(GMT+10:00) Port Moresby",
            'Australia/Sydney'     => "(GMT+10:00) Sydney",
            'Asia/Vladivostok'     => "(GMT+11:00) Vladivostok",
            'Asia/Magadan'         => "(GMT+12:00) Magadan",
            'Pacific/Auckland'     => "(GMT+12:00) Auckland",
            'Pacific/Fiji'         => "(GMT+12:00) Fiji",
        );
    }
}
