<?php
return [
    'collection' => 'm15',
    'exclude_crypt_fields' => [
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "status" => 'a2',
        "name" => 'a3',
        "apivendor" => 'a4',
        "partnerId" => 'a5',
        "p1" => 'a6',
        "p2" => 'a7',
        "p3" => 'a8',
        "p4" => 'a9',
        "p5" => 'a10',
        "p6" => 'a11',
        "p7" => 'a12',
        "p8" => 'a13',
        "p9" => 'a14',
        "p10" => 'a15',
        "p11" => 'a16',
        "p12" => 'a17',
        "p13" => 'a18',
        "p14" => 'a19',
        "p15" => 'a20',
        "last_call" => 'a21',
        "today_leads" => 'a22',
        "total_leads" => 'a23',
        "syncJob" => 'a24',
        "last_update" => 'a25',
        "today_ftd" => 'a26',
        "total_ftd" => 'a31',
        "today_revenue" => 'a27',
        "total_revenue" => 'a32',
        "created_at" => 'a28',
        "updated_at" => 'a29',
        "redirect_url" => 'a30',
        'countries' => 'a33',
        'languages' => 'a34',
        'regulated' => 'a35',
    ]
];
