<?php
return [
    'collection' => 'm9',
    'exclude_crypt_fields' => [
        "status"
    ],
    'fields' => [
        "clientId" => 'a1',
        "broker" => 'a2',
        "created_by" => 'a3',
        "type" => 'a4',
        "from" => 'a5',
        "to" => 'a6',
        "status" => 'a7',
        "leads" => 'a8',
        "cost" => 'a9',
        "total" => 'a10',
        "json_leads" => 'a11',
        "timestamp" => 'a12',
        "billing_entity" => 'a13',
        "billing_from" => 'a14',
        'payment_fee' => 'a15',
        "payment_method" => 'a16',
        "status_changed_date" => 'a17',
        "status_changed_user_id" => 'a18',
        "status_changed_user_ip" => 'a19',
        "status_changed_user_ua" => 'a20',
        "invoice" => 'a21',
        "final_approve_files" => 'a22',
        "final_status" => 'a23',
        "final_status_changed_date" => 'a24',
        "final_status_changed_user_id" => 'a25',
        "final_status_changed_user_ip" => 'a26',
        "final_status_changed_user_ua" => 'a27',
        "transaction_id" => 'a28',
        "adjustment_amount" => 'a29',
        "adjustment_description" => 'a30',
        "chargeback" => 'a31',
        "created_at" => 'a32',
        "updated_at" => 'a33',
        "priority" => 'a34',
        'final_status_date_pay' => 'a35',
    ]
];
