<?php
return [
    'collection' => 'm27',
    'exclude_crypt_fields' => [
        "master_approve_files",
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "endpoint" => 'a2',
        "created_by" => 'a3',
        "type" => 'a4',
        "from" => 'a5',
        "to" => 'a6',
        "status" => 'a7',
        "leads" => 'a8',
        "cost" => 'a9',
        "total" => 'a10',
        "json_leads" => 'a11',
        "timestamp" => 'a12',
        "status_changed_date" => 'a13',
        "status_changed_user_id" => 'a14',
        "status_changed_user_ip" => 'a15',
        "status_changed_user_ua" => 'a16',
        "transaction_id" => 'a17',
        "adjustment_amount" => 'a18',
        "adjustment_description" => 'a19',
        "chargeback" => 'a20',
        "final_approve_files" => 'a21',
        "final_status" => 'a22',
        "final_status_changed_date" => 'a23',
        "final_status_changed_user_id" => 'a24',
        "final_status_changed_user_ip" => 'a25',
        "final_status_changed_user_ua" => 'a26',
        "final_status_date_pay" => 'a27',
        "master_approve_invoice_files" => 'a28',
        "master_approve_files" => 'a29',
        "master_approve_note" => 'a30',
        "master_status" => 'a31',
        "master_status_changed_date" => 'a32',
        "master_status_changed_user_id" => 'a33',
        "master_status_changed_user_ip" => 'a34',
        "master_status_changed_user_ua" => 'a35',
        "payment_method" => 'a36',
        "sub_status" => 'a37',
        'hash_url' => 'a38',
        'proof_screenshots' => 'a39',
        'proof_description' => 'a40',
        "created_at" => 'a41',
        "updated_at" => 'a42',
    ]
];
