<?php
return [
    'collection' => 'm58',
    'exclude_crypt_fields' => [
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "Time" => 'a2',
        "hour" => 'a3',
        "day" => 'a4',
        "dayofweek" => 'a5',
        "month" => 'a6',
        "Timestamp" => 'a7',
        "CampaignId" => 'a8',
        "TrafficEndpoint" => 'a9',
        "gender" => 'a10',
        "age" => 'a11',
        "media_account_id" => 'a12',
        "voluum_click" => 'a13',
        "publisher_click" => 'a14',
        "publisher_id_voluum" => 'a15',
        "sub_publisher" => 'a16',
        "creative_id" => 'a17',
        "DOI" => 'a18',
        "first_name" => 'a19',
        "last_name" => 'a20',
        "email" => 'a21',
        "phone" => 'a22',
        "short_phone" => 'a23',
        "country_prefix" => 'a24',
        "country" => 'a25',
        "funnel_lp" => 'a26',
        "device_type" => 'a27',
        "language" => 'a28',
        "ip" => 'a29',
        "useragent" => 'a30',
        "device_version" => 'a31',
        "log_post" => 'a33',
        "log_server" => 'a33',
        "log_get" => 'a34',
        "log_php_input" => 'a35',
        "depositor" => 'a36',
        "syncedDepositRevenue" => 'a37',
        "syncedleadcost" => 'a38',
        "isCPL" => 'a39',
        "cost" => 'a40',
        "deposit_revenue" => 'a41',
        "status" => 'a42',
        "syncGoodLead" => 'a43',
        "syncBadLead" => 'a44',
        "deposit_disapproved" => 'a45',
    ]
];
