<?php
return [
    'collection' => 'm48',
    'exclude_crypt_fields' => [
        "blocked_offers",
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "full_name" => 'a2',
        "email" => 'a3',
        "email_md5" => 'a4',
        "password" => 'a5',
        "skype" => 'a6',
        "telegram" => 'a7',
        "whatsapp" => 'a8',
        "email_confirmed" => 'a9',
        "confirmCode" => 'a10',
        "under_review" => 'a11',
        "ip" => 'a12',
        "created_at" => 'a13',
        "updated_at" => 'a14',
        "blocked_offers" => 'a15',
        "name" => 'a16',
        "email_encrypted" => 'a17',
        "description" => 'a18',
        "token" => 'a19',
        "status" => 'a20',
        "qr_secret" => 'a21',
        "api_key" => 'a22',
        "account_password" => 'a23',
        "login_qr" => 'a24',
        "created_by" => 'a25',
        "account_manager" => 'a26',
        "postback" => 'a27',
        "event_postback" => 'a28',
        "blocked_offers_type" => 'a29',
        "manual_approve" => 'a30',
        "billing_manual_status" => 'a31',
        "aff_dashboard_pass" => 'a32',
    ]
];
