<?php
return [
    'collection' => 'm52',
    'exclude_crypt_fields' => [
        "tracking_country_link",
        "screenshot_image",
        "tags",
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "advertiserId" => 'a2',
        "name" => 'a3',
        "tracking_link" => 'a4',
        "tracking_preview_link" => 'a5',
        "token" => 'a6',
        "status" => 'a7',
        "advertiser_general_payout" => 'a8',
        "affiliate_general_payout" => 'a9',
        "advertiser_payout" => 'a10',
        "environment" => 'a11',
        "event_type" => 'a12',
        "category" => 'a13',
        "world_wide_targeting" => 'a14',
        "created_by" => 'a15',
        "created_at" => 'a16',
        "desktop_operating_system" => 'a17',
        "mobile_operating_system" => 'a18',
        "post_event" => 'a19',
        "screenshot_image" => 'a20',
        "tracking_country_link" => 'a21',
        "updated_at" => 'a22',
        "stat_today" => 'a23',
        "stat_general" => 'a24',
        "general_cap" => 'a25',
        "restrict_endpoints" => 'a26',
        "restrict_type" => 'a27',
        "force_sub_publisher" => 'a28',
        "tags" => 'a29',
        "description" => 'a30',
        "country" => 'a31',
        "language" => 'a32',
        "account_manager" => 'a33',
        "daily_cap" => 'a34',
        'check_max_mind' => 'a35',
        'time_start' => 'a36',
        'time_end' => 'a37',
        'blocked_schedule' => 'a38',
    ]
];
