<?php
return [
    'collection' => 'm4',
    'exclude_crypt_fields' => [
        "restricted_traffic",
        "restricted_endpoints",
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "partner_type" => 'a2',
        "partner_name" => 'a3',
        "business_partner_name" => 'a4',
        "partner_company" => 'a5',
        "partner_emailb" => 'a6',
        "partner_emailf" => 'a7',
        "partner_emailt" => 'a8',
        "country" => 'a9',
        "street" => 'a10',
        "city" => 'a11',
        "zipcode" => 'a12',
        "company_size" => 'a13',
        "company_type" => 'a14',
        "wechat" => 'a15',
        "skype" => 'a16',
        "api_key" => 'a17',
        "account_username" => 'a18',
        "account_password" => 'a19',
        "status" => 'a20',
        "net_terms" => 'a21',
        "today_leads" => 'a22',
        "total_leads" => 'a23',
        "master_partner" => 'a24',
        "is_assigned_master_partner" => 'a25',
        "today_ftd" => 'a26',
        "today_revenue" => 'a27',
        "total_ftd" => 'a28',
        "total_revenue" => 'a29',
        "languages" => 'a30',
        "restricted_traffic" => 'a31',
        "action_on_negative_balance" => 'a32',
        "financial_status" => 'a33',
        "account_manager" => 'a34',
        "balance" => 'a35',
        "balance_timestamp" => 'a36',
        "broker_crg_already_paid" => 'a37',
        "restricted_endpoints" => 'a38',
        "billing_manual_status" => 'a39',
        "token" => 'a40',
        "updated_at" => 'a41',
        "created_at" => "a42",
        "created_by" => 'a43',
        "forbidden_show_traffic_endpoint" => "a44",
        "tags" => 'a45',
    ]
];
