<?php
return [
    'collection' => 'm22',
    'exclude_crypt_fields' => [
        "permissions",
        "traffic_sources",
        "restricted_brokers_by_country",
        "traffic_sources",
        "blocked_funnels",
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "api_key" => 'a2',
        "account_password" => 'a3',
        "country" => 'a4',
        "company_type" => 'a5',
        "token" => 'a6',
        "status" => 'a7',
        "today_leads" => 'a8',
        "total_leads" => 'a9',
        "statusReporting" => 'a10',
        "statusDeposit" => 'a11',
        "aff_dashboard_pass" => 'a12',
        "endpoint_status" => 'a13',
        "login_qr" => 'a14',
        "statusMatching" => 'a15',
        "qr_secret" => 'a16',
        "master_partner" => 'a17',
        "is_assigned_master_partner" => 'a18',
        "postback" => 'a19',
        "account_manager" => 'a20',
        "today_cost" => 'a21',
        "today_deposits" => 'a22',
        "today_revenue" => 'a23',
        "lead_postback" => 'a24',
        "redirect_24_7" => 'a25',
        "replace_funnel_list" => 'a26',
        "billing_manual_status" => 'a27',
        "send_mismatch_again" => 'a28',
        "updated_at" => 'a29',
        "permissions" => 'a30',
        "total_cost" => 'a31',
        "marketing_suite_offers" => 'a32',
        "restricted_brokers_by_country" => 'a33',
        "probation" => 'a34',
        "balance" => 'a35',
        "balance_timestamp" => 'a36',
        "traffic_quality" => 'a37',
        "created_by" => 'a38',
        "created_at" => 'a39',
        "traffic_sources" => 'a40',
        "endpoint_type" => 'a41',
        "blocked_funnels" => 'a42',
        "deactivation_reason" => 'a43',
        "deactivation_reason_duplicated" => 'a44',
        "deactivation_reason_other" => 'a45',
        "marketing_suite_traffic_endpoinds" => 'a46',
        "restricted_brokers" => 'a47',
        "total_deposits" => 'a48',
        "total_revenue" => 'a49',
        "UnderReview" => 'a50',
        "ApplicationJson" => 'a51',
        "in_house" => 'a52',
        "tags" => 'a53',
    ]
];
