<?php
return [
    'collection' => 'm1',
    'exclude_crypt_fields' => [
        "account_email",
        'password',
        'roles',
        'permissions',
        'profile',
        'status'
    ],
    'fields' => [
        "clientId" => 'a1',
        "username" => 'a2',
        // "password" => 'a3',
        // "account_email" => 'a5',
        "name" => 'a6',
        "company_legal_name" => 'a7',
        "business_partner_name" => 'a8',
        "partner_company" => 'a9',
        "partner_emailb" => 'a10',
        "partner_emailf" => 'a11',
        "partner_emailt" => 'a12',
        "country" => 'a13',
        "street" => 'a14',
        "city" => 'a15',
        "zipcode" => 'a16',
        "company_size" => 'a17',
        "company_type" => 'a18',
        "wechat" => 'a19',
        "skype" => 'a20',
        "servingDomain" => 'a21',
        "category" => 'a22',
        "qr_secret" => 'a23',
        "qr_img" => 'a24',
        "status" => 'a25',
        "net_terms" => 'a26',
        "SlackID" => 'a27',
        "access" => 'a28',
        "token" => 'a29',
        "is_only_assigned_brokers" => 'a30',
        "active" => 'a31',
        "permissions" => 'a32',
        "is_admin" => 'a33',
        "last_auth_time" => 'a35',
        "roles" => 'a36',
        "updated_at" => 'a37',
        "profile" => 'a38',
        "created_at" => 'a39',
        "password2" => 'a40',
        "test_lead" => 'a41'
    ]
];
